### ISSUE TITLE
Sprint 2 Planning

### ISSUE THREAD

**Issue by abrahamkaunda** [Johnsont8-roehampton/SoftwareEngineering#2]
This issue is for planning Sprint 2 of the project. The aim of this sprint is to check that task management is set up and that the initial requirements gathering has taken place via user stories and use cases. By the end of this sprint, we aim to have completed at least 25% of the work for the project, based on our own estimates.

The following tasks must be completed during this sprint:

Define tasks as user stories and add them as issues on GitHub

Integrate project with Zube.io
Use Kanban/Project Board for task management
Use Sprint Boards for managing progress
Define full use cases for the project
Create Use Case Diagram for the project

Each task should be estimated for the effort required to complete it, and assigned to a team member for completion. Let's make sure to communicate and collaborate effectively during this sprint to ensure that we meet our goals.

**Comment by mspartho** [comment]
Note
