### ISSUE TITLE
 Sprint Backlog

### ISSUE THREAD

**Issue by abrahamkaunda** [Johnsont8-roehampton/SoftwareEngineering#3]
This issue is for creating the Sprint Backlog for our project. During the Sprint Planning meeting, we identified the features and requirements from the Product Backlog to be implemented during this sprint. The purpose of this issue is to break down those features and requirements into specific tasks that can be completed during the sprint.

Based on the Sprint Planning meeting, create a list of tasks to be completed during the sprint and add them to the Project Board on Trello. Use user stories and use cases defined in the Product Backlog as a reference. Each task should be specific, measurable, and achievable within the time frame of the sprint. Assign each task to team members as appropriate and set due dates. Review the Sprint Backlog at daily stand-up meetings and update as needed.

**Comment by mspartho** [comment]
Agreed
