### ISSUE TITLE
Sprint Review

### ISSUE THREAD

**Issue by abrahamkaunda** [Johnsont8-roehampton/SoftwareEngineering#5]
At the end of Sprint 2, we will conduct a Sprint Review to showcase the completed work
 and gather feedback from each member. The review will cover the following items:

Completed user stories and tasks
Progress made toward project goals
Any issues or obstacles encountered
Feedback from our lecturers 
The Sprint Review will be conducted on [Wednesdays during our Lab sessions], and all team members are expected to attend.

- We will use [WhatsApp Platoform] for our meetings as well.

**Comment by frankieg3** [comment]
While we have implemented them miss said we did so messily however at this stage of the course i do not believe it worth going back and tidying it up
