### ISSUE TITLE
Continuous Improvement Plan

### ISSUE THREAD

**Issue by abrahamkaunda** [Johnsont8-roehampton/SoftwareEngineering#9]
This issue will be used to document and track the ongoing efforts to improve the project development process. The team will regularly review and evaluate the process, and make adjustments as needed based on feedback from stakeholders and team members. The goal is to continuously improve the efficiency and effectiveness of the project development process over time.

**Comment by frankieg3** [comment]
based on the feedback from miss i worked on ensuring data from the database had been able to be called properly i also ensured that dynamic pug was working i also set up circleai for testing
